import { McpServer } from "@modelcontextprotocol/sdk/server/mcp";
import { Request } from "express";
import { IMcpTool } from "../types/IMcpTool";
import { z } from "zod";
import { FhirUtilities } from "../lib/fhir-utilities";
import { McpUtilities } from "../lib/mcp-utilities";
import { NullUtilities } from "../lib/null-utilities";
import { FhirClientInstance } from "../lib/fhir-client";
import { fhirR4 } from "@smile-cdr/fhirts";

class GetAppealPdfTool implements IMcpTool {
  registerTool(server: McpServer, req: Request) {
    server.registerTool(
      "GetAppealPdf",
      {
        description:
          "Generates a formatted appeal summary with all clinical evidence and citations. " +
          "Returns a structured document that includes patient demographics, clinical history, " +
          "denial details, and the medical necessity argument — ready for export or review.",
        inputSchema: {
          patientId: z
            .string()
            .describe(
              "The patient ID. Optional if patient context already exists via SHARP headers.",
            )
            .optional(),
          appealText: z
            .string()
            .describe(
              "The appeal letter text (typically from GenerateAppeal tool output).",
            ),
        },
      },
      async ({ patientId, appealText }) => {
        // Resolve patient ID
        if (!patientId) {
          patientId = NullUtilities.getOrThrow(
            FhirUtilities.getPatientIdIfContextExists(req),
            "Patient ID is required.",
          );
        }

        // Get patient info for the header
        let patientName = "Unknown Patient";
        let patientDob = "Unknown";
        let patientId_display = patientId;

        try {
          const patient = await FhirClientInstance.read<fhirR4.Patient>(
            req,
            `Patient/${patientId}`,
          );
          if (patient) {
            patientName =
              (patient.name?.[0]?.given?.join(" ") || "") +
              " " +
              (patient.name?.[0]?.family || "");
            patientName = patientName.trim() || "Unknown Patient";
            patientDob = patient.birthDate || "Unknown";
            patientId_display = patient.id || patientId;
          }
        } catch {
          // Use defaults
        }

        const today = new Date().toLocaleDateString("en-US", {
          year: "numeric",
          month: "long",
          day: "numeric",
        });

        // Build the formatted appeal document
        const document = [
          `# Prior Authorization Appeal`,
          ``,
          `**Date**: ${today}`,
          `**Patient**: ${patientName}`,
          `**Date of Birth**: ${patientDob}`,
          `**Patient ID**: ${patientId_display}`,
          `**FHIR Resource**: Patient/${patientId_display}`,
          ``,
          `---`,
          ``,
          appealText,
          ``,
          `---`,
          ``,
          `*This appeal was generated by AuthArmor MCP Server with inline FHIR resource citations.*`,
          `*All clinical claims reference specific FHIR resources from the patient's electronic health record.*`,
        ].join("\n");

        return McpUtilities.createTextResponse(document);
      },
    );
  }
}

export const GetAppealPdfToolInstance = new GetAppealPdfTool();
